### ISSUE TITLE
[Login] Form error does not manage focus

### ISSUE THREAD

**Issue by svinkle** [CovidShield/portal#3]
## Issue summary

Keyboard focus is not managed when the error message is displayed. As a result, there is no indication or notice of the error state. This may lead to a confusing user experience for screen reader users or zoom users with low vision.

<img width="392" alt="Screen Shot 2020-05-19 at 10 06 27 AM" src="https://user-images.githubusercontent.com/1392632/82336383-81447180-99b8-11ea-8da1-e76346c9c6bd.png">

#### HTML

```html
<h2 class="error" id="alert">Invalid username or password.</h2>
```

## Steps to reproduce

1. Go to https://portal.covidshield.app/ with with any supported browser
2. Submit the login form with invalid data

### Expected

- Focus will be sent to the Error message container.

### Actual

- Focus is sent to the top of the document.

## Recommendation

1. When the error message container is present, shift keyboard focus to this element via `focus()` event.
2. Apply the `tabindex="-1"` attribute in order for the element to receive focus.

#### HTML

```html
<h2 class="error" id="alert" tabindex="-1">Invalid username or password.</h2>
```

## Specifications

- **Component:** Login
- **WCAG Principle:** Understandable
- **WCAG SC:** 3.3.1 Error Identification
- **Severity:** High
- **Effort:** Medium

**Comment by dfmcphee** [comment]
Fixed by https://github.com/CovidShield/portal/pull/24
