### ISSUE TITLE
[Bug] Docker Compose setup doesn't work

### ISSUE THREAD

**Issue by jeffmaher** [CovidShield/portal#61]
Hey friends! Saw this and tried to get this running via Docker Compose, but it was not able to get it started.

# Steps

1. Clone repo and go to base directory
1. Edit `docker-compose.yml`'s [`KEY_CLAIM_HOST`](https://github.com/CovidShield/portal/blob/master/docker-compose.yml#L29) and [`KEY_CLAIM_TOKEN`](https://github.com/CovidShield/portal/blob/83e74be4d67024b02cb7411c338106b85abf230e/docker-compose.yml#L30) to reflect my [key-submission](https://github.com/CovidShield/server) setup.
1. Run `docker-compose up`

# Expected Result

Get login screen at `http://localhost:3000`.

# Actual Result

`portal_1` is not able to stay up. Log file: [docker-compose-log.txt](https://github.com/CovidShield/portal/files/4674217/docker-compose-log.txt)

Also, if you leave it up running long enough, `mysql_1` errors out with this line (amid `portal_1` going up and down constantly):

```
mysql_1   | 2020-05-24T18:36:12.033263Z 2 [Note] Access denied for user ' $MYSQL_USER'@'localhost' (using password: YES)`. 
```

Maybe or maybe not related?

**Comment by jeffmaher** [comment]
A colleague of mine spotted the code comment in `docker-compose.yml` that says to run `sh ./bootstrap.sh` to start up the app. Unfortunately, that also encountered errors. Here's the log:

[bootstrap_script_log.txt](https://github.com/CovidShield/portal/files/4674664/bootstrap_script_log.txt)

**Comment by honkfestival** [comment]
@jeffmaher we can finally reproduce this and are working on a fix. cc @Ginja

**Comment by shinebayar-g** [comment]
@jeffmaher How did you solve it? I'm getting exact same error when running `bundle exec rake portal:bootstrap`

Edit: Issue is solved by removing default credentials.yml.enc file.
