### ISSUE TITLE
[Bug] Local dev instructions result in Webpacker error

### ISSUE THREAD

**Issue by jeffmaher** [CovidShield/portal#62]
Followed the Local development instructions, but on the last step of going to the application in my browser, I got a Webpacker issue.

# Steps

(You can basically follow the instructions in the [README.md](https://github.com/CovidShield/portal/blob/83e74be4d67024b02cb7411c338106b85abf230e/README.md), but for accuracy's sake, placed verbatim what I did on my Mac just in case.)

1. Get `key-submission` running at `127.0.0.1:8000`: `git clone git@github.com:CovidShield/server.git && cd server && docker-compose up`
1. Clone and navigate into this repo on local machine
1. Install Node.js: `nvm install 12.16.3 && nvm use 12.16.3`
1. Install Ruby 2.7.1: `rbenv install 2.7.1 && rbenv local 2.7.1`
1. Install MySQL: `brew install mysql openssl`
1. Install Mysql2 Gem: `gem install mysql2 -- --with-cflags=\"-I/usr/local/opt/openssl@1.1/include\" --with-ldflags=\"-L/usr/local/opt/openssl@1.1/lib\"`
1. Run a local MySQL (running via Docker for tidiness/isolation): `rm -rf mysql-data && mkdir mysql-data && docker run -it --rm -p 3306:3306 --name portal-db -v $PWD/mysql-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=somepasswordhere -d mysql`
1. Confirm that the database is up in a database tool (TablePlus, in my case)
1. Update the `database.yml` file (under `default`): `username: root`, `password: somepasswordhere`, `host: 127.0.0.1`
1. Create/setup/seed the database: `bundle exec rake db:create && bundle exec rake db:setup && bundle exec rake db:seed`
1. Run the application: `KEY_CLAIM_HOST=127.0.0.1:8000 bundle exec rails s`
1. Go to `localhost:3000` in browser

# Expected Result

Portal web application to render a login or admin screen.

# Actual Result

![Screen Shot 2020-05-24 at 15 37 51](https://user-images.githubusercontent.com/950486/82763638-2b683300-9dd7-11ea-8c1f-c1e577cb084c.png)

# Other Thoughts

Probably Webpack isn't installed? I'll try that next, but, if that's it, probably should be mentioned in the dependencies. Also, if Docker Compose works (#61 ), these setup steps aren't required.

**Comment by jeffmaher** [comment]
Did `npm install webpack`, but it did not fix the bug.

**Comment by jeffmaher** [comment]
Next thing I've tried is `bundle exec rails assets:precompile`, but that results in an error:

```
...(lots of info statements)...
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
Exiting!
```

Will install Yarn and try again.

**Comment by jeffmaher** [comment]
Tried this next:

```
brew install yarn
bundle exec rails assets:precompile #This errors, suggests the next command
yarn add -D # This fails with error:Missing list of packages to add to your project.
```

**Comment by jeffmaher** [comment]
Next thing I tried:

```
./bin/webpack -w
# Asks to install webpack-cli, and I say yes
```

The Webpack server is running, so open a new terminal tab and try this:

```
KEY_CLAIM_HOST=127.0.0.1:8000 bundle exec rails s
```

And, it's up! 🥳 🎉 

(I have to bounce off for the day, but def should add to the docs.)

**Comment by LouisStAmour** [comment]
I don’t see an `npm install` or a `yarn` or `yarn install`. Try using the Dockerfile’s RUN commands as a set of instructions? https://github.com/CovidShield/portal/blob/master/Dockerfile#L37

As a sanity check, does docker-compose work locally for you?

**Comment by jeffmaher** [comment]
@LouisStAmour : A few comments up, did the NPM and Yarn commands (which aren't in the README). Unfortunately, Docker Compose didn't work for me either (filed #61 for that).

**Comment by jeffmaher** [comment]
Perhaps this last part is some aggressive CSRF caching?

This shows up in the logs:

```
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 570)
  
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

**Comment by TonyLeeVT** [comment]
Hello, I am also experiencing this same issue.  Did anyone make progress on troubleshooting it?  I added some Application trace info below.  Will post back if I find anything.

**Application Trace info is the following:**
app/views/layouts/application.html.erb:14
app/controllers/application_controller.rb:32:in `switch_locale'

![WebpackerError](https://user-images.githubusercontent.com/14014940/83164074-ca43a680-a0d9-11ea-9ebe-6be0d5b306dc.jpg)

**Comment by jeffmaher** [comment]
#73 fixes this issue for me, running via Docker Compose.
